#ifndef ZUMAHD_COMPONENTID_H
#define ZUMAHD_COMPONENTID_H

enum {
  COMPONENT_POSITION,
  COMPONENT_SPRITE,
  COMPONENT_TRANSFORM,
  COMPONENT_HUD,
  COMPONENT_FROG
};

#endif // ZUMAHD_COMPONENTID_H
