#pragma once

#include "../global/HQC.h"

void Store_LoadAll();

HQC_Texture     Store_GetTextureByID(int id);
HQC_Sprite      Store_GetSpriteByID(int id);
HQC_Animation   Store_GetAnimationByID(int id);
HQC_Sound       Store_GetSoundByID(int id);
HQC_Music       Store_GetMusicByID(int id);
HQC_Font        Store_GetFontByID(int id);

int Store_CountSounds();
int Store_CountSprites();


enum _TextureID {
	TEX_FROG,
	TEX_GAME_OBJECTS,
    TEX_GAME_HUD,
    TEX_MENU
};

enum _SoundID {
	SND_ACCURACY3,
    SND_BALLCLICK1,
    SND_BALLCLICK2,
    SND_BALLSDESTROYED1,
    SND_BALLSDESTROYED2,
    SND_BALLSDESTROYED3,
    SND_BALLSDESTROYED4,
    SND_BALLSDESTROYED5,
    SND_BOMBEXPLODE,
    SND_BUTTON1,
    SND_BUTTON2,
    SND_CHAIN1,
    SND_CHANT1,
    SND_CHANT14,
    SND_CHANT2,
    SND_CHANT3,
    SND_CHANT4,
    SND_CHANT5,
    SND_CHANT6,
    SND_CHANT8,
    SND_CHIME1,
    SND_CHORAL1,
    SND_COINGRAB,
    SND_EARTHQUAKE,
    SND_ENDOFLEVELPOP1,
    SND_EXTRALIFE,
    SND_FIREBALL1,
    SND_FROGLAND2,
    SND_GAPBONUS1,
    SND_GEMVANISHES,
    SND_JEWELAPPEAR,
    SND_LIGHTTRAIL2,
    SND_POP,
    SND_REVERSE1,
    SND_ROLLING,
    SND_SLOWDOWN1,
    SND_UFO1,
    SND_WARNING1,
};

enum _MusicID {
	MUS_GAME = 0,
	MUS_LOAD_SCREEN = 24,
	MUS_MAIN_MENU = 28,
	MUS_ADVENTURE = 32,
	MUS_GAUNTLET = 34,
	MUS_NEAR_HOLE = 36,
	MUS_WIN = 38,
	MUS_GAME_OVER = 39,
};

enum _FontID {
	// FONT_ARIAL_12,
	FONT_CANCUN_10,
	FONT_CANCUN_12,
	FONT_CANCUN_13,
	FONT_CANCUN_8,
	// FONT_CANCUN_FLOAT_14,
	FONT_NATIVE_ALIEN_48,
	// FONT_NATIVE_ALIEN_EXT_16,
	// FONT_NATIVE_ALIEN_EXT_18,
};

enum _SpriteID {
    SPR_FROG,
    SPR_FROG_PLATE,
    SPR_FROG_TONGUE,
    SPR_GAME_HUD_BORDER,
    SPR_GAME_HUD_LIVE,
    SPR_GAME_HUD_PROGRESS_BAR_GREEN,
    SPR_GAME_HUD_PROGRESS_BAR_YELLOW,
    SPR_GAME_HUD_BTN_MENU,
    SPR_GAME_HUD_BTN_MENU_HOVER,
    SPR_GAME_HUD_BTN_MENU_PRESSED,
    SPR_MENU_DIALOG_BOX_RECT_LT,
    SPR_MENU_DIALOG_BOX_RECT_CT,
    SPR_MENU_DIALOG_BOX_RECT_RT,
    SPR_MENU_DIALOG_BOX_RECT_LC,
    SPR_MENU_DIALOG_BOX_RECT_CC,
    SPR_MENU_DIALOG_BOX_RECT_RC,
    SPR_MENU_DIALOG_BOX_RECT_LB,
    SPR_MENU_DIALOG_BOX_RECT_CB,
    SPR_MENU_DIALOG_BOX_RECT_RB,
    SPR_MENU_SLIDER,
    SPR_MENU_SLIDER_THUMB,
    SPR_MENU_CHECKBOX_CHECKED,
    SPR_MENU_CHECKBOX,
    SPR_MENU_BUTTON,
    SPR_MENU_BUTTON_HOVER,
    SPR_MENU_BUTTON_PRESSED,
    SPR_MENU_HEAD,
    SPR_MENU_LOAD_BAR,
    SPR_MENU_SCREEN_LOADING,
    SPR_MENU_SCREEN_MAIN,
    SPR_MENU_SCREEN_GAUNTLET,
    SPR_MENU_MAIN_SUN,
    SPR_MENU_MAIN_SUN_LIGHT,
    SPR_MENU_SCREEN_MAIN_SKY,
    SPR_MENU_SCREEN_GAUNT_SKY,
    SPR_MENU_MAIN_BTN_OPTIONS,
    SPR_MENU_MAIN_BTN_OPTIONS_HOVER,
    SPR_MENU_MAIN_BTN_OPTIONS_PRESSED,
    SPR_MENU_MAIN_BTN_GAUNTLET,
    SPR_MENU_MAIN_BTN_GAUNTLET_HOVER,
    SPR_MENU_MAIN_BTN_GAUNTLET_PRESSED,
    SPR_MENU_MAIN_BTN_ADVENTURE,
    SPR_MENU_MAIN_BTN_ADVENTURE_HOVER,
    SPR_MENU_MAIN_BTN_ADVENTURE_PRESSED,
    SPR_MENU_MAIN_BTN_MOREGAMES,
    SPR_MENU_MAIN_BTN_MOREGAMES_HOVER,
    SPR_MENU_MAIN_BTN_MOREGAMES_PRESSED,
    SPR_MENU_MAIN_BTN_QUIT,
    SPR_MENU_MAIN_BTN_QUIT_HOVER,
    SPR_MENU_MAIN_BTN_QUIT_PRESSED,
    SPR_MENU_GAUNT_BTN_MAIN_MENU,
    SPR_MENU_GAUNT_BTN_MAIN_MENU_HOVER,
    SPR_MENU_GAUNT_BTN_MAIN_MENU_PRESSED,
    SPR_MENU_GAUNT_BTN_BACK,
    SPR_MENU_GAUNT_BTN_BACK_HOVER,
    SPR_MENU_GAUNT_BTN_BACK_PRESSED,
    SPR_MENU_GAUNT_BTN_PLAY,
    SPR_MENU_GAUNT_BTN_PLAY_HOVER,
    SPR_MENU_GAUNT_BTN_PLAY_PRESSED,
    SPR_MENU_GAUNT_BTN_NEXT,
    SPR_MENU_GAUNT_BTN_NEXT_HOVER,
    SPR_MENU_GAUNT_BTN_NEXT_PRESSED,
    SPR_MENU_GAUNT_BTN_RABBIT_DISABLED,
    SPR_MENU_GAUNT_BTN_RABBIT,
    SPR_MENU_GAUNT_BTN_RABBIT_HOVER,
    SPR_MENU_GAUNT_BTN_RABBIT_PRESSED,
    SPR_MENU_GAUNT_BTN_EAGLE_DISABLED,
    SPR_MENU_GAUNT_BTN_EAGLE,
    SPR_MENU_GAUNT_BTN_EAGLE_HOVER,
    SPR_MENU_GAUNT_BTN_EAGLE_PRESSED,
    SPR_MENU_GAUNT_BTN_JAGUAR_DISABLED,
    SPR_MENU_GAUNT_BTN_JAGUAR,
    SPR_MENU_GAUNT_BTN_JAGUAR_HOVER,
    SPR_MENU_GAUNT_BTN_JAGUAR_PRESSED,
    SPR_MENU_GAUNT_BTN_SUN_GOD_DISABLED,
    SPR_MENU_GAUNT_BTN_SUN_GOD,
    SPR_MENU_GAUNT_BTN_SUN_GOD_HOVER,
    SPR_MENU_GAUNT_BTN_SUN_GOD_PRESSED
};

enum _AnimationID {
    ANIM_FROG_BLINK,
    ANIM_FROG_BALLS,
    ANIM_BALL_BLUE,
    ANIM_BALL_GREEN,
    ANIM_BALL_YELLOW,
    ANIM_BALL_RED,
    ANIM_BALL_PURPLE,
    ANIM_BALL_GRAY,
    ANIM_COIN,
    ANIM_BALL_DESTROY,
    ANIM_EXPLOSION,
    ANIM_SKULL,
    ANIM_SPARKLE,
};