#pragma once

#include "../global/HQC.h"

void Store_LoadAll();

HQC_Texture Store_GetTextureByID(int id);
HQC_Sprite  Store_GetSpriteByID(int id);
HQC_Sound   Store_GetSoundByID(int id);
HQC_Music   Store_GetMusicByID(int id);

enum _TextureID {
	TEX_FROG,
	TEX_GAME_OBJECTS,
    TEX_GAME_HUD,
    TEX_MENU
};

enum _SoundID {
	SND_ACCURACY3,
    SND_BALLCLICK1,
    SND_BALLCLICK2,
    SND_BALLSDESTROYED1,
    SND_BALLSDESTROYED2,
    SND_BALLSDESTROYED3,
    SND_BALLSDESTROYED4,
    SND_BALLSDESTROYED5,
    SND_BOMBEXPLODE,
    SND_BUTTON1,
    SND_BUTTON2,
    SND_CHAIN1,
    SND_CHANT1,
    SND_CHANT14,
    SND_CHANT2,
    SND_CHANT3,
    SND_CHANT4,
    SND_CHANT5,
    SND_CHANT6,
    SND_CHANT8,
    SND_CHIME1,
    SND_CHORAL1,
    SND_COINGRAB,
    SND_EARTHQUAKE,
    SND_ENDOFLEVELPOP1,
    SND_EXTRALIFE,
    SND_FIREBALL1,
    SND_FROGLAND2,
    SND_GAPBONUS1,
    SND_GEMVANISHES,
    SND_JEWELAPPEAR,
    SND_LIGHTTRAIL2,
    SND_POP,
    SND_REVERSE1,
    SND_ROLLING,
    SND_SLOWDOWN1,
    SND_UFO1,
    SND_WARNING1,
};

enum _MusicID {
	MUS_GAME = 0,
	MUS_LOAD_SCREEN = 24,
	MUS_MAIN_MENU = 28,
	MUS_ADVENTURE = 32,
	MUS_GAUNTLET = 34,
	MUS_NEAR_HOLE = 36,
	MUS_WIN = 38,
	MUS_GAME_OVER = 39,
};

enum _FontID {
	FONT_ARIAL_12,
	FONT_CANCUN_10,
	FONT_CANCUN_12,
	FONT_CANCUN_13,
	FONT_CANCUN_8,
	FONT_CANCUN_FLOAT_14,
	FONT_NATIVE_ALIEN_48,
	FONT_NATIVE_ALIEN_EXT_16,
	FONT_NATIVE_ALIEN_EXT_18,
};